config/routes.rb
# Explicitly require "lib/peatio.rb".
# You may be surprised why this line also sits in config/application.rb.
# The same line sits in config/application.rb to allows early access to lib/peatio.rb.
# We duplicate line in config/routes.rb since routes.rb is reloaded when code is changed.
# The implementation of ActiveSupport's require_dependency makes sense to use it only in reloadable files.
# That's why it is here.
require_dependency 'peatio'

Dir['app/models/deposits/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }
Dir['app/models/withdraws/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do

  root 'welcome#index'

  get '/privacy' => 'application#privacy'
  # get '/auth/site/callback' => 'sessions#create', via: %i[get post]
  get '/verif_email/:salt' => 'sessions#verif_email', :constraints  => { :salt => /[^\+]+.*/ }, :as => :verif_email
  get '/login' => 'sessions#login', :as => :login
  get '/regist' => 'sessions#regist', :as => :regist
  match '/signup' => 'sessions#sign_up', via: %i[get post]
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: %i[get post]
  match '/privacy_agree' => 'sessions#privacy_agree', via: %i[get post]
  get '/forgot' => 'sessions#forgot', :as => :forgot
  match '/send_recover_pass' => 'sessions#send_recover_pass', via: %i[get post]
  get '/recover_pass/:salt' => 'sessions#recover_pass', :constraints  => { :salt => /[^\+]+.*/ }, :as => :recover_pass
  match '/send_recover_pass' => 'sessions#send_recover_pass', via: %i[get post]
  match '/reset_pass' => 'sessions#reset_pass', via: %i[get post]

  resource :member_mfa_session, only: %i(new create)
  match '/change_mfa_status' => 'sessions#change_mfa_status', via: %i[get post]

  # EPay
  match '/epay/paystatus' => 'epay#paystatus', via: %i[get post]
  match '/epay/payment' => 'epay#payment', via: %i[get post]
  match '/epay/nopayment' => 'epay#nopayment', via: %i[get post]

  # Chat
  get '/chat' => 'chats#show', :as => :show_chat
  post '/chat' => 'chats#create', :as => :create_chat

  scope module: :private do
    resources :settings, only: [:index]

    resources :withdraw_destinations, only: %i[ create update ]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    resources 'deposits/:currency', controller: 'deposits', as: 'deposit', only: %i[ destroy ] do
      collection { post 'gen_address' }
    end

    resources 'withdraws/:currency', controller: 'withdraws', as: 'withdraw', only: %i[ create destroy ]

    resources :account_versions, only: :index

    resources :exchange_assets, controller: 'assets'

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    resources :markets, only: [:show], constraints: MarketConstraint do
      resources :orders, only: %i[ index destroy ] do
        collection do
          post :clear
        end
      end
      resources :order_bids, only: [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, only: [:create] do
        collection do
          post :clear
        end
      end
    end

    post '/pusher/auth', to: 'pusher#auth'
  end

  get 'trading/:market_id', to: BlackHoleRouter.new, as: :trading

  scope ['', 'webhooks', ENV['WEBHOOKS_SECURE_URL_COMPONENT'].presence, ':ccy'].compact.join('/'), as: 'webhooks' do
    post 'tx_created', to: 'webhooks#tx_created'
  end

  draw :admin

  get '/swagger', to: 'swagger#index'

  mount APIv2::Mount => APIv2::Mount::PREFIX
  mount ManagementAPIv1::Mount => ManagementAPIv1::Mount::PREFIX
end

app/views/shared/_flash.html.erb
<div class="flash-message">
  <% if flash[:notice] %>
    <div class="alert alert-dismissable alert-custom-success alert-success">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-check"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:notice] %></span>
      </h2>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-dismissable alert-custom-danger alert-danger">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-times"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:alert] %></span>
      </h2>
    </div>
  <% end %>

  <% if flash[:info] %>
    <div class="alert alert-dismissable alert-custom-info alert-info">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-info"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:info] %></span>
      </h2>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<% if !current_user.nil? and current_user.privacy == 0%>
    <div class="privacy_popup">
        <a href="/privacy">Privacy policy</a> <a href="/privacy_agree"><button class="main-btn transparent-btn"><span>Agree</span></button></a>
    </div>
<% end %>

<!-- <footer>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="footer_title">Company</div>
                <div class="footer_list">
                    <ul>
                        <a href="#"><li>About us</li></a>
                        <a href="#"><li>News</li></a>
                        <a href="#"><li>Emergency Contacts</li></a>
                        <a href="#"><li>Contact</li></a>
                    </ul>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="footer_title">Customer Services</div>
                <div class="footer_list">
                    <ul>
                        <a href="#"><li>Blog</li></a>
                        <a href="#"><li>FAQs</li></a>
                        <a href="#"><li>Help</li></a>
                        <a href="#"><li>Terms and Conditions</li></a>
                    </ul>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="phone"><i class="fas fa-phone"></i>+357 123 123 12</div>
                <div class="address"><i class="fas fa-map-marker-alt"></i><span>Athinodorou Business Center 4th Floor, Suite 402 20  Charalambou Mouskou & Grigori Afxentiou Street Paphos, Paphos, Cyprus</span></div>
            </div>
            <div class="col-12 copyright">&copy; <%= Time.now.strftime("%Y")%> | <a href="#">Privacy Policy</a></div>
        </div>
    </div>
</footer> -->
<footer class="footer">
  <div class="container">
    <div class="footer__wrapper">
      <div class="column">
        <h6>Company</h6>
        <ul>
          <li>About us</li>
          <li>News</li>
          <li>Emergency Contacts</li>
          <li>Contact</li>
        </ul>
      </div>
      <div class="column">
        <h6>Customer Services</h6>
        <ul>
          <li>Blog</li>
          <li>FAQs</li>
          <li>Help</li>
          <li>Terms and Conditions</li>
        </ul>
      </div>
      <div class="column wide">
        <h6>Contact</h6>
          <ul>
            <li>
              <svg>
             <use xlink:href="<%= asset_path 'sprite-inline.svg#phone' %>"></use>
          </svg>
          <span>(+34) -653 378 193</span>
              </li>
              <li>
              <svg>
            <use xlink:href="<%= asset_path 'sprite-inline.svg#pin' %>"></use>
              </svg>
          <span>
            Athinodorou Business Center 4th Floor, Suite 402 20 Charalambou
            Mouskou & Grigori Afxentiou Street Paphos, Paphos, Cyprus
          </span>
            </li>
          </ul>
        </div>
      </div>
      <div class="copyright">
        <p>©2018 | Privacy Policy</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_frame.html.erb
<div class="container">
    <% if content_for?(:before) %>
    <%= yield(:before) %>
    <% end %>
    <div class="card-body">
        <div class="row">
            <div id="guide" class="col-12">
                <% if content_for?(:guide_title) %>
                <%= yield(:guide_title) %>
                <% else %>
                <h3><%= guide_title %></h3>
                <% end %>
                <p class="text-ignore"><%= guide_intro %></p>
                <% if content_for?(:guide) %>
                <%= yield(:guide) %>
                <% end %>
                <%= render 'shared/flash' %>
                <%= yield %>
            </div>
        </div>
        <% if content_for?(:secondary) %>
        <%= yield(:secondary) %>
        <% end %>
    </div>
    <% if content_for?(:after) %>
    <%= yield(:after) %>
    <% end %>
</div>

app/views/shared/_header.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="text-center navbar-brand" href="<%= root_path %>">
        <!-- <img class="nav-img" src="<%= ENV['LOGO_URL'] || image_path('logo.svg') %>"> -->
        <div class="text_site_logo">Innova.Exchange</div>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#top-navbar" aria-controls="top-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="top-navbar">
        <ul id="menu" class="navbar-nav mr-auto">
          <%= top_nav_link(t('header.market'), trading_path(current_market.id), 'exchange', target: '_blank') if !mfa_session? %>
          <%= top_nav_link(t('header.funds'), funds_path, 'money', controllers: ['funds']) if current_user %>
          <%# top_nav_link(t('header.assets'), exchange_assets_path, 'bar-chart-o') if current_user %>
          <%= top_nav_link(t('header.history'), order_history_path, 'book', controllers: ['history']) if current_user %>
        </ul>
        <ul class="navbar-nav ml-auto">
          <%= render partial: 'shared/header_profile_setting' if current_user %>
          <%= render partial: 'shared/header_lang_sel' %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_header_lang_sel.html.erb
<!-- <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
    <img src="<%= language_path %>"/>
    <b class="caret"></b>
  </a>
  <div id="languages" class="dropdown-menu">
    <% I18n.available_locales.each do |lang| %>
      <a class="dropdown-item" href="?lang=<%= lang %>">
        <img src="/languages/<%= lang || I18n.locale %>.png"/>
      </a>
    <% end %>
  </div>
</li> -->
<li class="nav-item dropdown languages">
    <ul>
        <li>
            <a class="nav-link <%= if I18n.locale.to_s == 'en' then 'active' end %>" href="?lang=en">En</a>
        </li>
        <li>
            <a class="nav-link <%= if I18n.locale.to_s == 'ru' then 'active' end %>" href="?lang=ru">Ru</a>
        </li>
    </ul>
</li>

app/views/shared/_header_profile_setting.html.erb
<% controllers = ['settings', 'dashboard'] %>
<% dropdown_class = (controllers & controller_path.split('/')).empty? ? '' : 'active' %>
<li class="nav-item dropdown account-settings text-left <%= dropdown_class %>">
  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
    <span><%= current_user.email %></span>
    <b class="caret"></b>
  </a>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="<%= settings_path %>">
      <i class="fa fa-user"></i><span><%= t('header.my_profile') %></span>
    </a>
    <% if is_admin? %>
      <a class="dropdown-item" href="<%= admin_dashboard_path %>">
        <i class="fa fa-dashboard"></i>
        <span><%= t('header.admin') %></span>
      </a>
    <% end %>
    <a class="dropdown-item" href="<%= main_app.signout_path %>">
      <i class="fa fa-sign-out"></i>
      <span><%= t('header.signout') %></span>
    </a>
  </div>
</li>

app/views/shared/_html5.html.erb
<!--[if lt IE 9]>
<%= javascript_include_tag 'html5' %>
<![endif]-->

app/views/shared/_meta.html.erb
<title><%= ENV.fetch('METADATA_TITLE') %></title>
<meta name="description" content="<%= ENV.fetch('METADATA_DESCRIPTION') %>">
<meta name="keywords" content="<%= ENV.fetch('METADATA_KEYWORDS') %>">

app/views/shared/_sentry.html.erb
<% if defined?(Raven) && ENV['SENTRY_DSN_FRONTEND'].present? %>
    <meta name="sentry-dsn" content="<%= ENV['SENTRY_DSN_FRONTEND'] %>">
<% end %>

app/views/shared/_theme.html.erb
<style>
  <% cache do %>
    <% style = File.read(File.expand_path('../_theme.scss.erb', __FILE__)) %>
    <%= Sass.compile(ERB.new(style).result, syntax: :scss).html_safe %>
  <% end %>
</style>

app/views/shared/_theme.scss.erb
.navbar-default {
  <% if ENV['HEADER_BACKGROUND_COLOR'] %>
    background-color: <%= ENV['HEADER_BACKGROUND_COLOR'] %>;
    border-color:     darken(<%= ENV['HEADER_BACKGROUND_COLOR'] %>, 5%);
  <% end %>

  <% if ENV['HEADER_BORDER_COLOR'] %>
    border-color: <%= ENV['HEADER_BORDER_COLOR'] %>;
  <% end %>

  .navbar-nav > li > a {
    <% if ENV['HEADER_LINK_COLOR'] %>
      color: <%= ENV['HEADER_LINK_COLOR'] %>;
    <% end %>
    &:hover, &:focus {
      <% if ENV['HEADER_LINK_HOVER_COLOR'] %>
        color: <%= ENV['HEADER_LINK_HOVER_COLOR'] %>;
      <% elsif ENV['HEADER_LINK_COLOR'] %>
        color: darken(<%= ENV['HEADER_LINK_COLOR'] %>, 10%);
      <% end %>
    }
  }

  .navbar-nav > .active > a {
    &, &:hover, &:focus {
      <% rubric_active_color = ENV['HEADER_RUBRIC_ACTIVE_COLOR'] || ENV['HEADER_LINK_COLOR'] %>
      <% if rubric_active_color %>
        color: <%= rubric_active_color %>;
      <% end %>

      <% if ENV['HEADER_RUBRIC_BACKGROUND_COLOR'] %>
        background-color: <%= ENV['HEADER_RUBRIC_BACKGROUND_COLOR'] %>;
      <% elsif ENV['HEADER_BACKGROUND_COLOR'] %>
        background-color: darken(<%= ENV['HEADER_BACKGROUND_COLOR'] %>, 10%);
      <% end %>
    }
  }
}